# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
  documentation:
    #        schemes: [http, https]
    info:
      title: SIRHPLUS API
      description: SIRHPLUS docs
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
            type: http
            scheme : Bearer
            bearerFormat: JWT
    security:
      - Bearer: []
  areas:
    path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
      - ^/api(?!/docs$)
    