nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN_LOCAL)%', '%env(CORS_ALLOW_ORIGIN_DEV)%']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
        expose_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN_LOCAL)%', '%env(CORS_ALLOW_ORIGIN_DEV)%']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization', 'Location']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
            expose_headers: ['Link', 'Location']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['*']
            max_age: 3600
            hosts: ['^api\.']
